eureka:
  client:
    serviceUrl:
      defaultZone: http://lover:lover@localhost:4444/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
lover:
  host: 192.168.1.10
  service:
    eureka:
      name: eureka
      port: 4444
    system:
      name: system
      port: 1001
